swagger: "2.0"
info:
  title: EDP Admin API
  description: API for EDP Admin
  version: "1.0"
paths:
  /api/user/login:
    post:
      tags:
        - EDP Uses
      summary: User Login
      description: Authenticate user credentials and perform login
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
          description: JSON object containing the username and password
      responses:
        200:
          description: Login successful
        401:
          description: Unauthorized - Invalid username or password
        500:
          description: Internal Server Error
  /api/user/create:
    post:
      tags:
        - EDP Uses
      summary: Create User
      description: Create a new user with the provided details
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
          description: JSON object containing the user details
      responses:
        200:
          description: User created successfully
        400:
          description: Bad Request - Required fields missing or empty
        500:
          description: Internal Server Error
  /api/user/delete:
    delete:
      tags:
        - EDP Uses
      summary: Delete User
      description: Delete a user with the provided username
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
          description: JSON object containing the username
      responses:
        200:
          description: User deleted successfully
        404:
          description: User not found
        500:
          description: Internal Server Error
  /api/user/search:
    get:
      tags:
        - EDP Uses
      summary: Search User
      description: Search for users based on provided filters
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
              username:
                type: string
              email:
                type: string
          description: JSON object containing the search filters
      responses:
        200:
          description: User found
        404:
          description: User not found
        500:
          description: Internal Server Error
  /api/run_edp_regression:
    post:
      tags:
        - EDP Regression
      summary: Run EDP Regression Test
      description: Runs the EDP regression test.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "title"
          in: "formData"
          description: "Title of the regression"
          required: true
          type: "string"
        - name: "creator"
          in: "formData"
          description: "Creator of the regression"
          required: true
          type: "string"
      responses:
        '200':
          description: EDP regression test executed successfully.
          schema:
            type: object
            properties:
              result:
                type: string
              output:
                type: string
              start_time:
                type: string
                format: date-time
              execution_time:
                type: string
              end_time:
                type: string
                format: date-time
              type:
                type: integer
  /api/download_edp_logs:
    get:
      tags:
        - EDP Regression
      summary: Download EDP Logs
      description: Downloads the EDP log file.
      responses:
        '200':
          description: EDP log file downloaded successfully
  /api/download_edp_reports:
    get:
      tags:
        - EDP Regression
      summary: Download EDP Reports
      description: Downloads the EDP report file.
      responses:
        '200':
          description: EDP report file downloaded successfully
  /api/preview_edp_log:
    get:
      tags:
        - EDP Regression
      summary: Preview EDP Log
      description: Previews the EDP log file.
      responses:
        '200':
          description: EDP log previewed successfully
  /api/preview_edp_report:
    get:
      tags:
        - EDP Regression
      summary: Preview EDP Report
      description: Previews the EDP report file.
      responses:
        '200':
          description: EDP report previewed successfully
  /api/update_edp_config:
    post:
      tags:
        - EDP Regression
      summary: Update EDP Config
      description: Updates the EDP config.
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: section
          in: formData
          type: string
          required: true
          description: The section to update in the EDP config.
        - name: key
          in: formData
          type: string
          required: true
          description: The key to update in the EDP config.
        - name: value
          in: formData
          type: string
          required: true
          description: The value to update in the EDP config.
      responses:
        '200':
          description: EDP config updated successfully.
  /edp_regression_list:
    get:
      tags:
        - "EDP Regression"
      summary: "Get EDP regression list"
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    title:
                      type: "string"
                    status:
                      type: "string"
                    createUser:
                      type: "string"
                    execution_time:
                      type: "string"
                    start_date:
                      type: "string"
                      format: "date-time"
                    end_date:
                      type: "string"
                      format: "date-time"
  /api/edp_performance_list:
    get:
      tags:
        - Performance List
      summary: Get EDP performance list
      parameters: [ ]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        createdTime:
                          type: string
                        source:
                          type: string
                        status:
                          type: string
        '500':
          description: Internal Server Error
  /api/performance_list/run_edp_performance:
    post:
      tags:
        - Performance List
      summary: Run EDP performance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  account:
                    type: string
                  Sender:
                    type: string
                  Target:
                    type: string
                  Host:
                    type: string
                  Port:
                    type: string
                  creator:
                    type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  creator:
                    type: string
                  status:
                    type: string
                  output:
                    type: string
                  start_time:
                    type: string
                  execution_time:
                    type: string
                  end_time:
                    type: string
                  type:
                    type: integer
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/performance_list/download_performance_logs:
    get:
      tags:
        - Performance List
      summary: Download performance logs
      parameters: [ ]
      responses:
        '200':
          description: Success
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request
        '404':
          description: File Not Found
        '500':
          description: Internal Server Error
  /api/performance_list/view_edp_performance_case:
    get:
      tags:
        - Performance List
      summary: View EDP performance case
      parameters: [ ]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  case_count:
                    type: integer
                  file_content:
                    type: string
        '404':
          description: File Not Found
        '500':
          description: Internal Server Error